services:
  - type: web
    name: node-EventRush
    env: node
    plan: free
    buildCommand: |
      npm install
      npx prisma generate
      npm run build
    startCommand: npm run start:migrate:prod
    envVars:
      - key: DATABASE_URL
        sync: false
