services:
  - type: web
    name: eventrush-api
    env: node
    plan: free
    buildCommand: |
      npm install
      npx prisma generate
      npm run build
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        sync: false   # tu le définis dans Render Dashboard
      - key: PORT
        value: 10000
